FROM alpine

RUN apk upgrade --no-cache \
    && apk add --no-cache ca-certificates tzdata ffmpeg \
    && update-ca-certificates

COPY ./web/dist ./web/dist
COPY ./one-api /
EXPOSE 3000
WORKDIR /data
ENTRYPOINT ["/one-api"]
